In [2]:
import pandas as pd
import numpy as np

In [3]:
#value counts

a = [1,1,1,2,3,4,4,5,5,6]
df = pd.Series(a)
df.value_counts()

1    3
4    2
5    2
2    1
3    1
6    1
Name: count, dtype: int64

In [4]:
ipl = pd.read_csv("C:/Users/Om/Downloads/ipl-matches.csv")
ipl['Player_of_Match'].value_counts()

Player_of_Match
AB de Villiers    25
CH Gayle          22
RG Sharma         18
DA Warner         18
MS Dhoni          17
                  ..
SA Asnodkar        1
GD McGrath         1
SM Katich          1
JDP Oram           1
MF Maharoof        1
Name: count, Length: 262, dtype: int64

In [5]:
df = ipl[(ipl['MatchNumber'] == 'Final') | (ipl['MatchNumber'] == 'Qualifier 1') | (ipl['MatchNumber'] == 'Qualifier 2')]
df['Player_of_Match'].value_counts()

Player_of_Match
JJ Bumrah            2
KA Pollard           2
M Vijay              2
YK Pathan            2
SK Raina             2
HH Pandya            1
RD Gaikwad           1
TA Boult             1
MP Stoinis           1
SR Watson            1
DA Miller            1
F du Plessis         1
VR Iyer              1
JC Buttler           1
BCJ Cutting          1
Washington Sundar    1
KV Sharma            1
KH Pandya            1
A Nehra              1
DA Warner            1
RG Sharma            1
AB de Villiers       1
UT Yadav             1
V Sehwag             1
MK Pandey            1
Harbhajan Singh      1
MS Bisla             1
MEK Hussey           1
CH Gayle             1
A Kumble             1
Name: count, dtype: int64

In [6]:
ipl.sample(5)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
650,548360,Mumbai,2012-05-09,2012,54,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Royal Challengers Bangalore,field,N,Royal Challengers Bangalore,Wickets,9.0,NaN,CH Gayle,"['JEC Franklin', 'SR Tendulkar', 'RG Sharma', ...","['TM Dilshan', 'CH Gayle', 'V Kohli', 'AB de V...",BF Bowden,VA Kulkarni
717,501255,Bangalore,2011-05-14,2011,58,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Royal Challengers Bangalore,Wickets,4.0,D/L,CH Gayle,"['CH Gayle', 'LA Pomersbach', 'V Kohli', 'AB d...","['JH Kallis', 'EJG Morgan', 'G Gambhir', 'MK T...",RE Koertzen,RB Tiffin
125,1254066,Chennai,2021-04-17,2021,9,Mumbai Indians,Sunrisers Hyderabad,"MA Chidambaram Stadium, Chepauk, Chennai",Mumbai Indians,bat,N,Mumbai Indians,Runs,13.0,NaN,KA Pollard,"['Q de Kock', 'RG Sharma', 'SA Yadav', 'Ishan ...","['DA Warner', 'JM Bairstow', 'MK Pandey', 'Vir...",CB Gaffaney,K Srinivasan
123,1254068,Mumbai,2021-04-18,2021,11,Punjab Kings,Delhi Capitals,"Wankhede Stadium, Mumbai",Delhi Capitals,field,N,Delhi Capitals,Wickets,6.0,NaN,S Dhawan,"['KL Rahul', 'MA Agarwal', 'CH Gayle', 'DJ Hoo...","['PP Shaw', 'S Dhawan', 'SPD Smith', 'RR Pant'...",AK Chaudhary,PR Reiffel
858,392217,Kimberley,2009-05-09,2009,37,Chennai Super Kings,Rajasthan Royals,De Beers Diamond Oval,Rajasthan Royals,bat,N,Chennai Super Kings,Wickets,7.0,NaN,S Badrinath,"['M Vijay', 'ML Hayden', 'SK Raina', 'S Badrin...","['GC Smith', 'NV Ojha', 'SA Asnodkar', 'RA Jad...",GAV Baxter,HDPK Dharmasena

In [7]:
ipl['TossDecision'].value_counts()

TossDecision
field    599
bat      351
Name: count, dtype: int64

In [8]:
#Sorting

ipl.sort_values('ID', ascending = False)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [61]:
students = pd.DataFrame(
    {
        'name':['Om','Ayush','Pratham',np.nan,'mrityunjay',np.nan,'Rahul',np.nan,'aditya',np.nan,'Om'],
        'college':['bit','iit','vit',np.nan,np.nan,'vlsi','ssit',np.nan,np.nan,'git','bit'],
        'branch':['eee','it','cse',np.nan,'me','ce','civ','cse','bio',np.nan,"eee"],
        'cgpa':[6.66,8.25,6.41,np.nan,5.6,9.0,7.4,10,7.4,np.nan,6.66],
        'package':[4,5,6,np.nan,6,7,8,9,np.nan,np.nan,4]

    }
)

students

          name college branch   cgpa  package
0           Om     bit    eee   6.66      4.0
1        Ayush     iit     it   8.25      5.0
2      Pratham     vit    cse   6.41      6.0
3          NaN     NaN    NaN    NaN      NaN
4   mrityunjay     NaN     me   5.60      6.0
5          NaN    vlsi     ce   9.00      7.0
6        Rahul    ssit    civ   7.40      8.0
7          NaN     NaN    cse  10.00      9.0
8       aditya     NaN    bio   7.40      NaN
9          NaN     git    NaN    NaN      NaN
10          Om     bit    eee   6.66      4.0

In [62]:
students.sort_values('package',na_position ='first', ascending = False)

          name college branch   cgpa  package
3          NaN     NaN    NaN    NaN      NaN
8       aditya     NaN    bio   7.40      NaN
9          NaN     git    NaN    NaN      NaN
7          NaN     NaN    cse  10.00      9.0
6        Rahul    ssit    civ   7.40      8.0
5          NaN    vlsi     ce   9.00      7.0
4   mrityunjay     NaN     me   5.60      6.0
2      Pratham     vit    cse   6.41      6.0
1        Ayush     iit     it   8.25      5.0
0           Om     bit    eee   6.66      4.0
10          Om     bit    eee   6.66      4.0

In [63]:
students.sort_values(['name','package'], ascending = [True, False])

          name college branch   cgpa  package
1        Ayush     iit     it   8.25      5.0
0           Om     bit    eee   6.66      4.0
10          Om     bit    eee   6.66      4.0
2      Pratham     vit    cse   6.41      6.0
6        Rahul    ssit    civ   7.40      8.0
8       aditya     NaN    bio   7.40      NaN
4   mrityunjay     NaN     me   5.60      6.0
7          NaN     NaN    cse  10.00      9.0
5          NaN    vlsi     ce   9.00      7.0
3          NaN     NaN    NaN    NaN      NaN
9          NaN     git    NaN    NaN      NaN

In [64]:
#Ranking function

run = pd.read_csv("C:/Users/Om/Downloads/batsman_runs_ipl.csv")
run.head(5)

           batter  batsman_run
0  A Ashish Reddy          280
1        A Badoni          161
2      A Chandila            4
3        A Chopra           53
4     A Choudhary           25

In [65]:
run["Ranking"] = run['batsman_run'].rank(ascending = False)
run

             batter  batsman_run  Ranking
0    A Ashish Reddy          280    166.5
1          A Badoni          161    226.0
2        A Chandila            4    535.0
3          A Chopra           53    329.0
4       A Choudhary           25    402.5
..              ...          ...      ...
600      Yash Dayal            0    594.0
601   Yashpal Singh           47    343.0
602     Younis Khan            3    547.5
603    Yuvraj Singh         2754     27.0
604          Z Khan          117    256.0

[605 rows x 3 columns]

In [66]:
run.sort_values("Ranking")

             batter  batsman_run  Ranking
569         V Kohli         6634      1.0
462        S Dhawan         6244      2.0
130       DA Warner         5883      3.0
430       RG Sharma         5881      4.0
493        SK Raina         5536      5.0
..              ...          ...      ...
570  V Pratap Singh            0    594.0
63     Abdur Razzak            0    594.0
562          U Kaul            0    594.0
65       Akash Deep            0    594.0
57           AS Roy            0    594.0

[605 rows x 3 columns]

In [67]:
#sort index

students.sort_index(ascending = False)

          name college branch   cgpa  package
10          Om     bit    eee   6.66      4.0
9          NaN     git    NaN    NaN      NaN
8       aditya     NaN    bio   7.40      NaN
7          NaN     NaN    cse  10.00      9.0
6        Rahul    ssit    civ   7.40      8.0
5          NaN    vlsi     ce   9.00      7.0
4   mrityunjay     NaN     me   5.60      6.0
3          NaN     NaN    NaN    NaN      NaN
2      Pratham     vit    cse   6.41      6.0
1        Ayush     iit     it   8.25      5.0
0           Om     bit    eee   6.66      4.0

In [68]:
#set index

run.set_index("batter", inplace = True)
run

                batsman_run  Ranking
batter
A Ashish Reddy          280    166.5
A Badoni                161    226.0
A Chandila                4    535.0
A Chopra                 53    329.0
A Choudhary              25    402.5
...                     ...      ...
Yash Dayal                0    594.0
Yashpal Singh            47    343.0
Younis Khan               3    547.5
Yuvraj Singh           2754     27.0
Z Khan                  117    256.0

[605 rows x 2 columns]

In [69]:
run.reset_index(inplace = True)
run

             batter  batsman_run  Ranking
0    A Ashish Reddy          280    166.5
1          A Badoni          161    226.0
2        A Chandila            4    535.0
3          A Chopra           53    329.0
4       A Choudhary           25    402.5
..              ...          ...      ...
600      Yash Dayal            0    594.0
601   Yashpal Singh           47    343.0
602     Younis Khan            3    547.5
603    Yuvraj Singh         2754     27.0
604          Z Khan          117    256.0

[605 rows x 3 columns]

In [70]:
#Unique

temp = pd.Series([1,1,2,2,2,2,4,5,6,np.nan,np.nan])
temp

0     1.0
1     1.0
2     2.0
3     2.0
4     2.0
5     2.0
6     4.0
7     5.0
8     6.0
9     NaN
10    NaN
dtype: float64

In [71]:
len(temp.unique())

6

In [72]:
temp.nunique()

5

In [73]:
len(ipl['Season'].unique())

15

In [74]:
ipl['Season'].nunique()

15

In [75]:
students['name'][students['name'].isnull()]

3    NaN
5    NaN
7    NaN
9    NaN
Name: name, dtype: object

In [76]:
students['name'][students['name'].notnull()]

0             Om
1          Ayush
2        Pratham
4     mrityunjay
6          Rahul
8         aditya
10            Om
Name: name, dtype: object

In [77]:
students

          name college branch   cgpa  package
0           Om     bit    eee   6.66      4.0
1        Ayush     iit     it   8.25      5.0
2      Pratham     vit    cse   6.41      6.0
3          NaN     NaN    NaN    NaN      NaN
4   mrityunjay     NaN     me   5.60      6.0
5          NaN    vlsi     ce   9.00      7.0
6        Rahul    ssit    civ   7.40      8.0
7          NaN     NaN    cse  10.00      9.0
8       aditya     NaN    bio   7.40      NaN
9          NaN     git    NaN    NaN      NaN
10          Om     bit    eee   6.66      4.0

In [78]:
#drop
students.dropna(how = "any")

       name college branch  cgpa  package
0        Om     bit    eee  6.66      4.0
1     Ayush     iit     it  8.25      5.0
2   Pratham     vit    cse  6.41      6.0
6     Rahul    ssit    civ  7.40      8.0
10       Om     bit    eee  6.66      4.0

In [79]:
students

          name college branch   cgpa  package
0           Om     bit    eee   6.66      4.0
1        Ayush     iit     it   8.25      5.0
2      Pratham     vit    cse   6.41      6.0
3          NaN     NaN    NaN    NaN      NaN
4   mrityunjay     NaN     me   5.60      6.0
5          NaN    vlsi     ce   9.00      7.0
6        Rahul    ssit    civ   7.40      8.0
7          NaN     NaN    cse  10.00      9.0
8       aditya     NaN    bio   7.40      NaN
9          NaN     git    NaN    NaN      NaN
10          Om     bit    eee   6.66      4.0

In [89]:
students.dropna(subset = ['name','college'])

       name college branch  cgpa  package
0        Om     bit    eee  6.66      4.0
1     Ayush     iit     it  8.25      5.0
2   Pratham     vit    cse  6.41      6.0
6     Rahul    ssit    civ  7.40      8.0
10       Om     bit    eee  6.66      4.0

In [81]:
students

          name college branch   cgpa  package
0           Om     bit    eee   6.66      4.0
1        Ayush     iit     it   8.25      5.0
2      Pratham     vit    cse   6.41      6.0
3          NaN     NaN    NaN    NaN      NaN
4   mrityunjay     NaN     me   5.60      6.0
5          NaN    vlsi     ce   9.00      7.0
6        Rahul    ssit    civ   7.40      8.0
7          NaN     NaN    cse  10.00      9.0
8       aditya     NaN    bio   7.40      NaN
9          NaN     git    NaN    NaN      NaN
10          Om     bit    eee   6.66      4.0

In [90]:
#fill
students['name'].fillna('Unknow')

0             Om
1          Ayush
2        Pratham
3         Unknow
4     mrityunjay
5         Unknow
6          Rahul
7         Unknow
8         aditya
9         Unknow
10            Om
Name: name, dtype: object

In [91]:
students['cgpa'].fillna(students['cgpa'].mean())

0      6.660000
1      8.250000
2      6.410000
3      7.486667
4      5.600000
5      9.000000
6      7.400000
7     10.000000
8      7.400000
9      7.486667
10     6.660000
Name: cgpa, dtype: float64

In [92]:
students['name'].fillna(method = 'bfill')

C:\Users\Om\AppData\Local\Temp\ipykernel_5676\1287350698.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  students['name'].fillna(method = 'bfill')

0             Om
1          Ayush
2        Pratham
3     mrityunjay
4     mrityunjay
5          Rahul
6          Rahul
7         aditya
8         aditya
9             Om
10            Om
Name: name, dtype: object

In [85]:
#Duplicated handling

students.drop_duplicates()

         name college branch   cgpa  package
0          Om     bit    eee   6.66      4.0
1       Ayush     iit     it   8.25      5.0
2     Pratham     vit    cse   6.41      6.0
3         NaN     NaN    NaN    NaN      NaN
4  mrityunjay     NaN     me   5.60      6.0
5         NaN    vlsi     ce   9.00      7.0
6       Rahul    ssit    civ   7.40      8.0
7         NaN     NaN    cse  10.00      9.0
8      aditya     NaN    bio   7.40      NaN
9         NaN     git    NaN    NaN      NaN

In [86]:
students.drop_duplicates(keep = 'last')

          name college branch   cgpa  package
1        Ayush     iit     it   8.25      5.0
2      Pratham     vit    cse   6.41      6.0
3          NaN     NaN    NaN    NaN      NaN
4   mrityunjay     NaN     me   5.60      6.0
5          NaN    vlsi     ce   9.00      7.0
6        Rahul    ssit    civ   7.40      8.0
7          NaN     NaN    cse  10.00      9.0
8       aditya     NaN    bio   7.40      NaN
9          NaN     git    NaN    NaN      NaN
10          Om     bit    eee   6.66      4.0

In [87]:
#drop by index
students.drop(index = [0,4,5])

       name college branch   cgpa  package
1     Ayush     iit     it   8.25      5.0
2   Pratham     vit    cse   6.41      6.0
3       NaN     NaN    NaN    NaN      NaN
6     Rahul    ssit    civ   7.40      8.0
7       NaN     NaN    cse  10.00      9.0
8    aditya     NaN    bio   7.40      NaN
9       NaN     git    NaN    NaN      NaN
10       Om     bit    eee   6.66      4.0

In [88]:
#drop by columns

students.drop(columns = ['branch','package'])

          name college   cgpa
0           Om     bit   6.66
1        Ayush     iit   8.25
2      Pratham     vit   6.41
3          NaN     NaN    NaN
4   mrityunjay     NaN   5.60
5          NaN    vlsi   9.00
6        Rahul    ssit   7.40
7          NaN     NaN  10.00
8       aditya     NaN   7.40
9          NaN     git    NaN
10          Om     bit   6.66